# sally's hyprland conf teehee

# monitors
source = ~/.config/hypr/monitors.conf

# programs
source = ~/.config/hypr/programs.conf

# autostart
source = ~/.config/hypr/autostart.conf

# environment variables
source = ~/.config/hypr/env.conf

# look and feel
source = ~/.config/hypr/look.conf

# input
source = ~/.config/hypr/input.conf

# keybindings
source = ~/.config/hypr/keybindings.conf

# windows
source = ~/.config/hypr/windows.conf
