#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config height 35
spacebar -m config title off
spacebar -m config spaces on
spacebar -m config clock on
spacebar -m config power on
spacebar -m config padding_left 20
spacebar -m config padding_right 20
spacebar -m config spacing_left 25
spacebar -m config spacing_right 15
spacebar -m config text_font "GohuFont uni14 Nerd Font:Regular:14.0"
spacebar -m config icon_font "GohuFont uni14 Nerd Font:Regular:14.0"
spacebar -m config background_color 0x10202020
spacebar -m config foreground_color 0xffb8b8b8
spacebar -m config space_icon_color 0xffb8b8b8
spacebar -m config power_icon_color 0xffb8b8b8
spacebar -m config battery_icon_color 0xffb8b8b8
spacebar -m config dnd_icon_color 0xffb8b8b8
spacebar -m config clock_icon_color 0xffb8b8b8
spacebar -m config power_icon_strip B C
spacebar -m config space_icon_strip I II III IV V VI VII VIII IX X
# spacebar -m config space_icon SPC
spacebar -m config clock_icon CLK
spacebar -m config dnd_icon DND
spacebar -m config clock_format "%d/%m/%y %I::%M %p"

echo "spacebar configuration loaded.."
