#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
ALT_FONT="GohuFont uni14 Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    position=top \
    y_offset=5 \
    height=32 \
    color=0x00494d64 \
    margin=10 \
    sticky=on \
    padding_left=5 \
    padding_right=5 \
    notch_width=188 \
    display=main

sketchybar --default \
    background.height=32 \
    icon.color=0xff24273a \
    icon.font="$FONT_FACE:Medium:20.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xff24273a \
    label.font="$ALT_FONT:Regular:14.0" \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5 \
    background.corner_radius=5 
    # background.padding_right=5 

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5bde6 \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    background.padding_right=5 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked mouse.scrolled

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
