import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 5

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
normal.family = "JetBrainsMono Nerd Font"
# normal.family = "GohuFont uni14 Nerd Font"
# normal.family = "FiraCode Nerd Font Mono"

size = 15
