import = ["~/.config/alacritty/themes/themes/gruvbox_material.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 9

decorations = "Buttonless"

opacity = 1.0
blur = true

option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
normal.family = "JetBrainsMono Nerd Font"
# normal.family = "GohuFont uni14 Nerd Font"
# normal.family = "FiraCode Nerd Font Mono"

size = 15
